### ISSUE TITLE
File storage

### ISSUE THREAD

**Issue by JanKrb** [KrbDevelopment/Articly-Backend#2]
**Is your feature request related to a problem? Please describe.**
It's rather enhancing the user experience and expanding use cases for articly.

**Describe the solution you'd like**
I'd like to add some sort of storage, where different groups/roles could add resources like images, sketches or even something like worksheets.

**Comment by Lukas2112** [comment]
I could imagine that make a lot of sense if you could share files from your Nextcloud instance and include the share link.
In my opinion, this would prevent attachments to the respective topic from quickly becoming obsolete because there would be no duplicates.

**Comment by JanKrb** [comment]
I wouldn't be a fan of supporting Nextcloud links only, but in addition to your suggestion, we could try to support all kind of direct download links. The problem I see with only including Nextcloud links, the file will disappear/won't be available anymore, as soon as the cloud doesn't exist anymore. Looking forward for feedback about my suggestion for the "Nextcloud integration".

**Comment by Lukas2112** [comment]
> I wouldn't be a fan of supporting Nextcloud links only, but in addition to your suggestion, we could try to support all kind of direct download links. The problem I see with only including Nextcloud links, the file will disappear/won't be available anymore, as soon as the cloud doesn't exist anymore. Looking forward for feedback about my suggestion for the "Nextcloud integration".

I think I have phrased it in a somewhat misleading way - sorry for that. Of course, my idea of storing sharing links (including sharing passwords, if assigned) would be applicable to (privacy-friendly) clouds - I just wanted to illustrate my idea with the example of Nextcloud.
