### ISSUE TITLE
Art. 15 GDPR "Right of access for the data subject

### ISSUE THREAD

**Issue by Lukas2112** [KrbDevelopment/Articly-Backend#6]
**Does your feature request relate to a problem? Please describe it.
Not quite - more like legal security under the General Data Protection Regulation (GDPR).

**Describe the solution you want**.
A tabular listing (parameters on the left, content on the right) of what information is stored by the service from you (email, etc.) 

**Describe the alternatives you have considered**.
Provide the nformation as an archive.

**Additional Context**.
The secure German email provider mailbox.org has implemented something like this, as described above. Hence the idea.

As far as I can see, this idea is both a back- and a frontend story.

**Comment by JanKrb** [comment]
Please specify your issue. Does this relate to the software itself (for example the readme) or something like a privacy statement? The users them self can see which data is saved inside their profile.

**Comment by NinoKrb** [comment]
I see the point but i guess it doesn`t belongs to the backend repository. Please recreate the issue in our frontend repository (https://github.com/KrbDevelopment/Articly-Frontend).
