### ISSUE TITLE
Search parameter for "posts/unauthorized" route

### ISSUE THREAD

**Issue by NinoKrb** [KrbDevelopment/Articly-Backend#7]
**Is your feature request related to a problem? Please describe.**
The route "posts/unauthorized" has no working search parameter. 

**Describe the solution you'd like**
Please add the search parameter function so that it can be used in the post authorizations pages.

**Comment by NinoKrb** [comment]
Please also add for "posts/reports"

**Comment by JanKrb** [comment]
> **Is your feature request related to a problem? Please describe.**
> The route "posts/unauthorized" has no working search parameter.
> 
> **Describe the solution you'd like**
> Please add the search parameter function so that it can be used in the post authorizations pages.


Solved in https://github.com/KrbDevelopment/Articly-Backend/commit/61cf4ae82e7bfd93ad2e0419a54a24eb0a3baa91



> Please also add for "posts/reports"

https://github.com/KrbDevelopment/Articly-Backend/commit/c50d6844f4c7560251f7e0bb2fe94780932cc476
