### ISSUE TITLE
Notification route with parameter does not return

### ISSUE THREAD

**Issue by NinoKrb** [KrbDevelopment/Articly-Backend#9]
**Describe the bug**
The route `api/notifications/own does` not return a value if you specify the parameter `?unseen=1`.

**To Reproduce**
1. Go in Postman
2. Create a new GET request
3. Use `api/notifications/own?unseen=1` as your request URL
4. Look at the return values

**Expected behavior**
Get back the correct and unread notifications.

**Additional context**
Please fix the error so that the notification modal works normally again.

**Comment by JanKrb** [comment]
Fixed in issue https://github.com/KrbDevelopment/Articly-Backend/commit/77be37a2c1bc9c981a23cc9c9e84b5460274164f
